
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js 관례상 로컬 전용 값(예: Vercel CLI가 심어준 DATABASE_URL)은 .env.local에 들어가므로,
// .env를 먼저 읽고 .env.local이 있으면 덮어쓴다(Prisma CLI는 기본적으로 .env.local을 모른다).
loadEnv();
loadEnv({ path: ".env.local", override: true });

export default defineConfig({
  earlyAccess: true,
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
});
